export const USERS_REPOSITORY_TOKEN = Symbol('USERS_REPOSITORY_TOKEN');
export const SESSIONS_REPOSITORY_TOKEN = Symbol('SESSIONS_REPOSITORY_TOKEN');
export const ACCOUNTS_REPOSITORY_TOKEN = Symbol('ACCOUNTS_REPOSITORY_TOKEN');
export const PASSWORD_HASHER_TOKEN = Symbol('PASSWORD_HASHER_TOKEN');
export const BAN_STATUS_QUERY_TOKEN = Symbol('BAN_STATUS_QUERY_TOKEN');
